### ISSUE TITLE
the dimensions of bilateral_grid and guidemap_guide in slice operation are not match

### ISSUE THREAD

**Issue by simpler66** [Zhou-Yijie/MSLTNet#3]
the coef is obtained by:
coeff = F.grid_sample(bilateral_grid, guidemap_guide, align_corners=True)
where the dimension of bilateral_grid and guidemap_guide is Nx12x6x16x16 and Nx1xHxWx3 respectively. 
in my opinion, the dimension of guidemap_guide should be Nx1x3xHxW. Could you confirm if the code is incorrect

**Comment by Zhou-Yijie** [comment]
On network.py line 76 , the dimensions of guidemap_guide are rearranged to fit the 5D input (N, D_out, H_out, W_out, 3) of torch.nn.functional.grid_sample. So guidemap_guide is Nx1xHxWx3 here.

**Comment by simpler66** [comment]
ok, thanks for your work and reply.
